import { forwardRef, useImperativeHandle, useRef } from 'react'
// import Button from './UI/Button'


const Help = forwardRef(function ModalMenu(_,ref) {
  const dialog = useRef()
  useImperativeHandle(ref, () => {
    return {
      open() {
        dialog.current.showModal()
      },
      close() {
        dialog.current.close()
      }
    }
  })
  return (
    <dialog  ref={dialog} className='max-w-[25rem] max-h-screen backdrop:bg-sky-300   flex-col space-y-2 p-1 rounded-md'>
     
      <div className={`p-2 rounded-lg mt-2 bg-green-600`}>
        <h3 className="text-white text-center">Co je lepší</h3>
      </div>
      <div className={`p-2 rounded-lg bg-green-300 h-[34rem] px-5 pt-5 overflow-auto`}>
     <p>Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!Lpossimus expedita esse, ipsa eligendi, soluta, rerum consectetur voluptatibus Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aliquam rem repudiandae accusamus possimus laborum ducimus molestiae, dolor doloremque sit dolores perferendis odio voluptatum cupiditate quasi quisquam perspiciatis provident explicabo!
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus adipisci modi nulla quaerat! Nostrum ullam maxime dolore aliquam perspiciatis ut inventore, non minus voluptatem vero eos, rerum possimus accusantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit magnam dolor natus laborum aperiam. Totam esse, dignissimos non cum necessitatibus et corporis mollitia dolore inventore adipisci fugit libero illo asperiores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi optio sed laudantium! Iste perferendis, impedit vel laborum odit excepturi hic obcaecati qui quasi illum aperiam rerum dignissimos blanditiis porro quod!
     </p>
      
    </div>
      <form method="dialog">
        <button className='
        w-full border bg-green-600 rounded-lg'>Close</button></form>
    </dialog>
  )
})

export default Help;
